import { Head } from "next/document";

const CommonHead = () => {
  return (
    <Head>
      <title>Cisrup</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="darkreader" content="nah"></meta>
    </Head>
  );
};
export default CommonHead;
